### ISSUE TITLE
有一个名词写错了

### ISSUE THREAD

**Issue by holynewbie** [hjzheng/CUF_PPTs#1]
如图所示（好像不能传图，直接上url吧）

[http://ww4.sinaimg.cn/large/7156d016jw1f2n0eznh9wj20xr0krk1v.jpg](url)

应该将第二个“绘制过程”更改为“布局过程”。

**Comment by hjzheng** [comment]
看到了，多谢了！我抽时间已改！！！
![image](https://cloud.githubusercontent.com/assets/4166657/14309565/ce9bfc8c-fc0f-11e5-8d08-c15ba930ad0f.png)
